// Database Giấc Mơ - Bản Cập Nhật Siêu Cấp (100+ Điềm Báo)
// Update: 04/04/2026

const DreamDB = [
    // --- CHỦ ĐỀ: ĂN UỐNG & SINH HOẠT ---
    { key: "ăn cơm", numbers: "00, 19", soul: "Cuộc sống bình yên, no đủ sắp tới." },
    { key: "ăn tiệc", numbers: "83, 87", soul: "Cẩn thận hao tài tốn của vào việc vô bổ." },
    { key: "uống rượu", numbers: "45, 90", soul: "Có chuyện vui sắp tới nhưng đừng quá chén." },
    { key: "uống bia", numbers: "08, 18", soul: "Bạn bè tụ tập, chuẩn bị có kèo vui." },
    { key: "ăn thịt gà", numbers: "28, 68", soul: "Lộc ăn kéo đến, có khách quý ghé thăm." },
    { key: "ăn cá", numbers: "05, 60", soul: "Tiền bạc hanh thông, vạn sự như ý." },
    { key: "ăn thịt bò", numbers: "41, 91", soul: "Sức khỏe dồi dào, năng lượng tràn đầy." },
    { key: "ăn bánh ngọt", numbers: "02, 52", soul: "Tình cảm ngọt ngào, có người thầm thương." },
    { key: "uống cà phê", numbers: "11, 21", soul: "Đang tỉnh táo để đón nhận cơ hội mới." },
    { key: "đói bụng", numbers: "13, 93", soul: "Đừng quá lo lắng về tài chính hiện tại." },
    { key: "nấu ăn", numbers: "38, 83", soul: "Bà đang chăm chút cho hạnh phúc gia đình." },

    // --- CHỦ ĐỀ: ĐỒNG NGHIỆP, CÔNG VIỆC & GAME ---
    { key: "sếp", numbers: "21, 26, 76", soul: "Áp lực công việc đang đè nặng, hãy nghỉ ngơi." },
    { key: "đồng nghiệp", numbers: "14, 41", soul: "Cẩn thận lời ăn tiếng nói nơi công sở." },
    { key: "bị đuổi việc", numbers: "04, 44", soul: "Cánh cửa này đóng lại, cánh cửa khác sẽ mở ra." },
    { key: "thăng chức", numbers: "56, 65", soul: "Vận may công danh đang đến rất gần." },
    { key: "đi làm muộn", numbers: "06, 60", soul: "Bà đang sợ bỏ lỡ một cơ hội quan trọng." },
    { key: "viết code", numbers: "01, 10", soul: "Mọi rắc rối sẽ được giải quyết logic thôi." },
    { key: "chơi game", numbers: "23, 46, 64", soul: "Đang khao khát chiến thắng trong một dự án." },
    { key: "bug game", numbers: "00, 11", soul: "Cẩn thận tiểu tiết, đừng để sai sót nhỏ làm hỏng việc lớn." },
    { key: "họp hành", numbers: "35, 53", soul: "Có tin đồn không hay, cần giữ bình tĩnh." },
    { key: "nhận lương", numbers: "27, 72", soul: "Thành quả xứng đáng cho sự nỗ lực." },

    // --- CHỦ ĐỀ: NGƯỜI THÂN, BẠN BÈ & CẢM XÚC ---
    { key: "bố mẹ", numbers: "24, 84", soul: "Gia đạo an vui, nên quan tâm người thân hơn." },
    { key: "anh em", numbers: "01, 10", soul: "Có người giúp đỡ trong lúc hoạn nạn." },
    { key: "vợ chồng", numbers: "02, 20", soul: "Tình cảm đi lên, hiểu nhau hơn." },
    { key: "trẻ con", numbers: "09, 19, 91", soul: "Có quý nhân phù trợ sắp xuất hiện." },
    { key: "người yêu cũ", numbers: "31, 62, 91", soul: "Chuyện cũ đã qua, hãy sống cho hiện tại." },
    { key: "bạn cũ", numbers: "38, 83", soul: "Sắp nhận được tin tức bất ngờ từ phương xa." },
    { key: "cãi nhau", numbers: "36, 63", soul: "Sắp có sự thay đổi lớn trong quan hệ." },
    { key: "khóc", numbers: "85, 87", soul: "Nỗi buồn sẽ qua, niềm vui sẽ trở lại." },
    { key: "cười", numbers: "14, 41", soul: "Tinh thần lạc quan là chìa khóa thành công." },
    { key: "đám cưới", numbers: "02, 22", soul: "Có sự kết nối mới, quan hệ mới tốt đẹp." },
    { key: "đám tang", numbers: "34, 35", soul: "Buông bỏ được gánh nặng tâm lý bấy lâu." },
    { key: "người chết", numbers: "03, 43, 83", soul: "Sinh dữ tử lành, đừng quá sợ hãi." },

    // --- CHỦ ĐỀ: ĐỒ VẬT & GIAO THÔNG ---
    { key: "xe máy", numbers: "42, 52, 72", soul: "Chuẩn bị cho một hành trình mới." },
    { key: "ô tô", numbers: "08, 80", soul: "Sắp đạt được thành quả lớn lao." },
    { key: "xe đạp", numbers: "02, 20", soul: "Cần nỗ lực hơn nữa để đạt mục tiêu." },
    { key: "máy bay", numbers: "05, 50, 95", soul: "Tầm nhìn của bà đang vươn xa tầm quốc tế." },
    { key: "tàu thủy", numbers: "11, 16", soul: "Mọi việc trôi chảy như nước xuôi dòng." },
    { key: "điện thoại", numbers: "01, 11", soul: "Có tin nhắn quan trọng mang lại vận may." },
    { key: "máy tính", numbers: "22, 25", soul: "Công việc đòi hỏi sự tập trung cao độ." },
    { key: "tiền lẻ", numbers: "03, 07", soul: "Cẩn thận chi tiêu linh tinh, lãng phí." },
    { key: "tiền đô", numbers: "66, 88", soul: "Tài lộc cực lớn, con số đại phát." },
    { key: "vàng", numbers: "37, 92", soul: "Cơ hội đầu tư vàng đang ở trước mắt." },
    { key: "nhà mới", numbers: "03, 33", soul: "An cư lạc nghiệp, điềm báo ổn định." },
    { key: "quần áo", numbers: "06, 60", soul: "Sắp có sự thay đổi về diện mạo hoặc vị thế." },
    { key: "nhẫn kim cương", numbers: "44, 88", soul: "Cam kết bền vững hoặc tình duyên viên mãn." },

    // --- CHỦ ĐỀ: CON VẬT & THIÊN NHIÊN ---
    { key: "rắn", numbers: "32, 42, 72", soul: "Cẩn thận tiểu nhân nhưng cũng là điềm báo trí tuệ." },
    { key: "chó", numbers: "29, 59, 95", soul: "Có bạn bè trung thành giúp đỡ." },
    { key: "mèo", numbers: "18, 58", soul: "Cần chú ý hơn đến sức khỏe bản thân." },
    { key: "chuột", numbers: "15, 51", soul: "Cẩn thận mất đồ hoặc bị soi mói." },
    { key: "voi", numbers: "13, 53", soul: "Quý nhân to lớn sắp xuất hiện giúp đỡ bà." },
    { key: "hổ", numbers: "06, 60", soul: "Bà đang có sức mạnh át vía đối thủ." },
    { key: "rồng", numbers: "10, 50, 90", soul: "Đỉnh cao danh vọng, vận thế đang lên." },
    { key: "ngựa", numbers: "12, 52, 92", soul: "Công việc tiến triển thần tốc." },
    { key: "lợn", numbers: "07, 47, 87", soul: "Lộc lá dồi dào, ăn nên làm ra." },
    { key: "chim bay", numbers: "56, 65", soul: "Tự do và khao khát đổi mới không gian sống." },
    { key: "mưa", numbers: "07, 47, 67", soul: "Mọi khó khăn sẽ được gột rửa sạch sẽ." },
    { key: "nắng", numbers: "15, 51", soul: "Hy vọng mới, ánh sáng mới cho dự án." },
    { key: "bão", numbers: "29, 69", soul: "Sắp có biến động mạnh, cần giữ vững tay chèo." },
    { key: "biển", numbers: "00, 11", soul: "Tâm hồn bao dung, bình tĩnh trước sóng gió." },

    // --- CHỦ ĐỀ: SỰ VIỆC & HOẠT ĐỘNG ---
    { key: "đi lạc", numbers: "21, 31", soul: "Bà đang mất phương hướng, cần ngồi lại suy ngẫm." },
    { key: "bị đuổi đánh", numbers: "08, 58", soul: "Áp lực cuộc sống khiến bà mệt mỏi." },
    { key: "nhảy múa", numbers: "26, 62", soul: "Tâm trạng đang rất tốt, tràn đầy cảm hứng." },
    { key: "đi tắm", numbers: "39, 93", soul: "Sắp trút bỏ được phiền muộn." },
    { key: "đi bơi", numbers: "14, 41", soul: "Đang cố gắng thích nghi với môi trường mới." },
    { key: "đi học", numbers: "17, 71", soul: "Bà cần trau dồi thêm kiến thức chuyên môn." },
    { key: "thi cử", numbers: "26, 62", soul: "Thử thách sắp tới sẽ giúp bà khẳng định mình." },
    { key: "trúng số", numbers: "00, 55, 99", soul: "May mắn bất ngờ, nhưng đừng quá trông chờ." },
    { key: "mất tiền", numbers: "01, 10", soul: "Của đi thay người, đừng quá buồn lòng." },
    { key: "nhặt được tiền", numbers: "48, 84", soul: "Có lộc nhỏ, hãy chia sẻ để nhân đôi niềm vui." },
    { key: "bay lượn", numbers: "05, 50", soul: "Ý tưởng sáng tạo đang thăng hoa." },
    { key: "chìm xuống nước", numbers: "07, 70", soul: "Cần chú ý hơn đến cảm xúc bên trong." },
    { key: "đi du lịch", numbers: "12, 21", soul: "Bà cần một kỳ nghỉ để tái tạo năng lượng." },
    { key: "bị bệnh", numbers: "15, 51", soul: "Hãy chú trọng vào sức khỏe ngay lúc này." },
    { key: "uống thuốc", numbers: "02, 20", soul: "Sự hàn gắn, chữa lành đang diễn ra." },
    { key: "nhà cháy", numbers: "07, 27, 67", soul: "Năng lượng bùng nổ, làm gì cũng thắng." },
    { key: "xây nhà", numbers: "14, 41", soul: "Đang xây dựng nền móng cho tương lai bền vững." },
    { key: "mất xe", numbers: "07, 28, 92", soul: "Đề phòng mất mát nhỏ hoặc thay đổi kế hoạch." },
    { key: "bắt cá", numbers: "01, 81", soul: "Nắm bắt được cơ hội kinh doanh tốt." },
    { key: "tặng quà", numbers: "18, 81", soul: "Bà là người hào phóng, hậu vận sẽ rất tốt." },
    { key: "nhận quà", numbers: "05, 55", soul: "Sắp có niềm vui bất ngờ từ người thân." },
    { key: "gặp ma", numbers: "02, 72", soul: "Đừng sợ, đó là biểu hiện của sự lo âu thôi." },
    { key: "đi chùa", numbers: "05, 45", soul: "Tâm hồn đang tìm kiếm sự bình yên." },
    { key: "sinh con", numbers: "09, 19, 91", soul: "Khởi đầu mới đầy hứa hẹn cho dự án Mỡ." },
    { key: "cắt tóc", numbers: "89, 98", soul: "Thay đổi tư duy, loại bỏ cái cũ." },
    { key: "soi gương", numbers: "07, 77", soul: "Bà cần nhìn nhận lại bản thân một cách thẳng thắn." },
    { key: "trèo cây", numbers: "04, 44", soul: "Đang nỗ lực vượt qua khó khăn để thành công." },
    { key: "ngã", numbers: "16, 61", soul: "Cẩn thận trong các quyết định quan trọng." },
    { key: "hôn", numbers: "00, 48, 84", soul: "Sự kết nối, giao thoa cảm xúc đang thăng hoa." },
    { key: "máu", numbers: "19, 69, 96", soul: "Có sự biến động mạnh, cần chuẩn bị tâm lý." },
    { key: "rụng răng", numbers: "03, 30", soul: "Cẩn thận lời nói hoặc lo lắng về quyền lực." },
    { key: "vàng giả", numbers: "08, 80", soul: "Đừng tin vào những vẻ hào nhoáng bên ngoài." },
    { key: "nhẫn cưới", numbers: "01, 10", soul: "Gắn kết lâu dài, tin vui trong tình cảm." }
];
