// Database Giấc Mơ - Phiên Bản ĐẠI TOÀN THƯ (Gấp 3 lần dung lượng)
// Cập nhật: 04/04/2026

const DreamDB = [
    // --- CHỦ ĐỀ: "THÔ NHƯNG THẬT" & CẢM XÚC MẠNH ---
    { key: "cứt", numbers: "31, 36, 63", soul: "Tiền bạc sắp dính đầy người, lộc lá bất ngờ." },
    { key: "phân", numbers: "00, 50", soul: "Điềm báo tài chính đang có sự chuyển dịch lớn." },
    { key: "hố xí", numbers: "08, 09", soul: "Sắp thoát khỏi nợ nần hoặc rắc rối đeo bám." },
    { key: "đi vệ sinh", numbers: "34, 43", soul: "Hãy xả bỏ những năng lượng tiêu cực trong lòng." },
    { key: "đánh nhau", numbers: "03, 07, 59", soul: "Sắp có xung đột ý tưởng, hãy giữ bình tĩnh." },
    { key: "đấm", numbers: "13, 31", soul: "Áp lực dồn nén bấy lâu cần được giải tỏa ngay." },
    { key: "chửi lộn", numbers: "25, 52", soul: "Cẩn thận thị phi, nên giữ mồm giữ miệng nơi đông người." },
    { key: "bị đánh", numbers: "05, 55", soul: "Sinh dữ tử lành, có người đang âm thầm gánh vác hộ bạn." },
    { key: "đâm chém", numbers: "11, 22", soul: "Cẩn thận với những quyết định mang tính cắt đứt đột ngột." },
    { key: "máu", numbers: "19, 69, 96", soul: "Biến động mạnh về cảm xúc, cần chuẩn bị tâm lý vững." },
    { key: "giết người", numbers: "83, 47", soul: "Bạn đang muốn rũ bỏ hoàn toàn quá khứ để làm lại." },
    { key: "khóc", numbers: "85, 87", soul: "Nỗi buồn sẽ qua, một niềm vui lớn đang chờ phía trước." },
    { key: "cười", numbers: "14, 41", soul: "Tinh thần lạc quan là chìa khóa mở ra thành công." },
    { key: "tự tử", numbers: "01, 10", soul: "Đừng bi quan, đây là điềm báo bạn sắp đổi vận cực mạnh." },

    // --- CHỦ ĐỀ: ĂN UỐNG & SINH HOẠT ---
    { key: "ăn cơm", numbers: "00, 19", soul: "Cuộc sống bình yên, no đủ sắp tới." },
    { key: "ăn tiệc", numbers: "83, 87", soul: "Cẩn thận hao tài vào những việc vô bổ." },
    { key: "uống rượu", numbers: "45, 90", soul: "Có chuyện vui nhưng đừng để quá chén mà hỏng việc." },
    { key: "uống bia", numbers: "08, 18", soul: "Bạn bè tụ tập, chuẩn bị có kèo vui vẻ." },
    { key: "ăn thịt gà", numbers: "28, 68", soul: "Lộc ăn kéo đến, sắp có khách quý ghé thăm." },
    { key: "ăn cá", numbers: "05, 60", soul: "Tiền bạc hanh thông, vạn sự như ý." },
    { key: "ăn bánh ngọt", numbers: "02, 52", soul: "Tình cảm ngọt ngào, có người đang thầm thương bạn." },
    { key: "uống cà phê", numbers: "11, 21", soul: "Bạn đang rất tỉnh táo để đón nhận cơ hội mới." },
    { key: "đói bụng", numbers: "13, 93", soul: "Đừng quá lo lắng về tài chính, mọi chuyện sẽ ổn." },
    { key: "nấu ăn", numbers: "38, 83", soul: "Bạn đang chăm chút rất tốt cho hạnh phúc gia đình." },
    { key: "ăn quả", numbers: "39, 49", soul: "Thành quả ngọt ngào sau thời gian dài nỗ lực." },
    { key: "ăn trộm", numbers: "01, 90", soul: "Cẩn thận mất mát nhỏ hoặc bị người khác nẫng tay trên." },
    { key: "đi chợ", numbers: "25, 52", soul: "Bạn đang cân nhắc giữa nhiều lựa chọn quan trọng." },
    { key: "uống trà", numbers: "56, 65", soul: "Tâm hồn đang tìm kiếm sự thanh tịnh, nhẹ nhàng." },
    { key: "hút thuốc", numbers: "08, 85", soul: "Sức khỏe cần được chú ý, đừng để căng thẳng kéo dài." },

    // --- CHỦ ĐỀ: CÔNG VIỆC, ĐỒNG NGHIỆP & SỰ NGHIỆP ---
    { key: "sếp", numbers: "21, 26, 76", soul: "Áp lực công việc đang đè nặng, hãy nghỉ ngơi." },
    { key: "đồng nghiệp", numbers: "14, 41", soul: "Cẩn thận lời ăn tiếng nói nơi công sở." },
    { key: "bị đuổi việc", numbers: "04, 44", soul: "Cánh cửa này đóng, cánh cửa khác lớn hơn sẽ mở." },
    { key: "thăng chức", numbers: "56, 65", soul: "Vận may công danh đang đến rất gần." },
    { key: "đi làm muộn", numbers: "06, 60", soul: "Bạn đang sợ bỏ lỡ cơ hội quan trọng trong dự án." },
    { key: "họp", numbers: "35, 53", soul: "Có tin đồn không hay, cần giữ cái đầu lạnh." },
    { key: "nhận lương", numbers: "27, 72", soul: "Thành quả xứng đáng cho những ngày OT miệt mài." },
    { key: "ký hợp đồng", numbers: "01, 10", soul: "Sự nghiệp bước sang trang mới đầy hứa hẹn." },
    { key: "máy tính", numbers: "22, 25", soul: "Hãy back-up dữ liệu ngay, cẩn thận sai sót kỹ thuật." },
    { key: "viết code", numbers: "00, 11", soul: "Mọi rắc rối sẽ được giải quyết bằng tư duy logic." },
    { key: "thất nghiệp", numbers: "00, 04", soul: "Thời gian để bạn tái cấu trúc lại kế hoạch cuộc đời." },
    { key: "phỏng vấn", numbers: "12, 21", soul: "Bạn đang khao khát khẳng định giá trị bản thân." },

    // --- CHỦ ĐỀ: NGƯỜI THÂN, BẠN BÈ & GIA ĐÌNH ---
    { key: "bố mẹ", numbers: "24, 84", soul: "Gia đạo an vui, nên dành thêm thời gian cho gia đình." },
    { key: "anh em", numbers: "01, 10", soul: "Có người thân thiết sẽ hỗ trợ bạn lúc khó khăn." },
    { key: "vợ chồng", numbers: "02, 20", soul: "Mối quan hệ đang trở nên khăng khít và thấu hiểu." },
    { key: "trẻ con", numbers: "09, 19, 91", soul: "Quý nhân phù trợ sắp xuất hiện bất ngờ." },
    { key: "người yêu cũ", numbers: "31, 62, 91", soul: "Hãy để quá khứ ngủ yên, tập trung cho tương lai." },
    { key: "bạn cũ", numbers: "38, 83", soul: "Sắp có tin tức bất ngờ từ một người quen xa cách." },
    { key: "cãi nhau", numbers: "36, 63", soul: "Sắp có thay đổi lớn trong các mối quan hệ xã hội." },
    { key: "đám cưới", numbers: "02, 22", soul: "Sự kết nối mới, quan hệ mới rất tốt đẹp." },
    { key: "đám tang", numbers: "34, 35", soul: "Bạn đã buông bỏ được gánh nặng tâm lý bấy lâu." },
    { key: "người chết", numbers: "03, 43, 83", soul: "Sinh dữ tử lành, một sự chuyển mình tích cực." },
    { key: "ông bà", numbers: "15, 51", soul: "Bạn đang được bề trên chở che và ban phước." },
    { key: "người lạ", numbers: "27, 72", soul: "Cẩn thận với những lời mời mọc quá hấp dẫn." },
    { key: "sinh con", numbers: "09, 19, 91", soul: "Khởi đầu mới đầy hứa hẹn cho dự án tâm huyết." },
    { key: "ngoại tình", numbers: "69, 96", soul: "Tâm hồn đang khao khát sự đổi mới hoặc cảm giác lạ." },

    // --- CHỦ ĐỀ: ĐỒ VẬT, NHÀ CỬA & TÀI CHÍNH ---
    { key: "xe máy", numbers: "42, 52, 72", soul: "Sẵn sàng cho một hành trình mới thú vị." },
    { key: "ô tô", numbers: "08, 80", soul: "Sắp đạt được thành quả và sự công nhận lớn." },
    { key: "điện thoại", numbers: "01, 11", soul: "Sắp có cuộc gọi mang tính bước ngoặt." },
    { key: "tiền đô", numbers: "66, 88", soul: "Tài lộc cực lớn, con số mang lại đại phát." },
    { key: "vàng", numbers: "37, 92", soul: "Cơ hội đầu tư quý giá đang ở ngay trước mắt." },
    { key: "nhà mới", numbers: "03, 33", soul: "An cư lạc nghiệp, điềm báo cuộc sống ổn định." },
    { key: "quần áo", numbers: "06, 60", soul: "Sắp có sự thay đổi về diện mạo hoặc vị thế." },
    { key: "chìa khóa", numbers: "01, 10", soul: "Bạn sắp tìm ra giải pháp cho một vấn đề bế tắc." },
    { key: "nhẫn", numbers: "01, 10", soul: "Sự gắn kết bền lâu hoặc tin vui tình cảm." },
    { key: "mất xe", numbers: "07, 28, 92", soul: "Của đi thay người, hãy cẩn thận hành trang sắp tới." },
    { key: "nhặt tiền", numbers: "48, 84", soul: "Có lộc nhỏ, hãy chia sẻ niềm vui với mọi người." },
    { key: "ví tiền", numbers: "67, 76", soul: "Tài chính cần được quản lý chặt chẽ hơn." },
    { key: "trang sức", numbers: "23, 32", soul: "Vẻ ngoài của bạn đang rất thu hút người khác." },

    // --- CHỦ ĐỀ: CON VẬT & THIÊN NHIÊN ---
    { key: "rắn", numbers: "32, 42, 72", soul: "Cẩn thận tiểu nhân nhưng cũng là điềm báo trí tuệ." },
    { key: "chó", numbers: "29, 59, 95", soul: "Những người bạn trung thành luôn sát cánh bên bạn." },
    { key: "mèo", numbers: "18, 58", soul: "Hãy chú trọng chăm sóc sức khỏe bản thân." },
    { key: "chuột", numbers: "15, 51", soul: "Cẩn thận mất đồ hoặc có người đang soi mói." },
    { key: "voi", numbers: "13, 53", soul: "Quý nhân hoặc thế lực lớn sẽ giúp đỡ bạn." },
    { key: "rồng", numbers: "10, 50, 90", soul: "Vận thế rực rỡ, thành công vang dội đang tới." },
    { key: "chim", numbers: "56, 65", soul: "Khao khát tự do và đổi mới không gian sống." },
    { key: "mưa", numbers: "07, 47, 67", soul: "Mọi muộn phiền sẽ được gột rửa sạch sẽ." },
    { key: "lửa", numbers: "07, 27, 67", soul: "Năng lượng bùng nổ, làm gì cũng dễ thành." },
    { key: "hổ", numbers: "06, 60", soul: "Bạn đang sở hữu sức mạnh át vía đối thủ." },
    { key: "ngựa", numbers: "12, 52, 92", soul: "Công việc sẽ tiến triển thần tốc như ngựa phi." },
    { key: "lợn", numbers: "07, 47, 87", soul: "Lộc lá dồi dào, chuẩn bị thu hoạch thành quả." },
    { key: "nhện", numbers: "33, 73", soul: "Có khách quý hoặc đối tác quan trọng sắp tìm đến." },
    { key: "bướm", numbers: "19, 59, 99", soul: "Vẻ đẹp phù du, hãy tỉnh táo trước những lời mời gọi." },
    { key: "rùa", numbers: "27, 67", soul: "Chậm mà chắc, kiên trì sẽ hái quả ngọt." },
    { key: "cá", numbers: "01, 81", soul: "Nắm bắt được cơ hội kinh doanh cực kỳ béo bở." },
    { key: "ong", numbers: "16, 56, 96", soul: "Sự cần cù của bạn sắp được đền đáp xứng đáng." },

    // --- CHỦ ĐỀ: HOẠT ĐỘNG, SỰ VIỆC & KHÁC ---
    { key: "đi lạc", numbers: "21, 31", soul: "Bạn đang mất phương hướng, hãy dành thời gian tĩnh tâm." },
    { key: "đi tắm", numbers: "39, 93", soul: "Sắp trút bỏ phiền muộn, bắt đầu lại đầy sảng khoái." },
    { key: "trúng số", numbers: "00, 55, 99", soul: "May mắn bất ngờ, nhưng đừng quá lạm dụng vận may." },
    { key: "mất tiền", numbers: "01, 10", soul: "Của đi thay người, đừng quá u sầu vì vật chất." },
    { key: "cắt tóc", numbers: "89, 98", soul: "Thay đổi tư duy, loại bỏ những thứ cũ kỹ lỗi thời." },
    { key: "rụng răng", numbers: "03, 30", soul: "Đang lo lắng về quyền lực hoặc sức ảnh hưởng bản thân." },
    { key: "gặp ma", numbers: "02, 72", soul: "Chỉ là biểu hiện của lo âu, hãy thư giãn đầu óc." },
    { key: "bay", numbers: "05, 50", soul: "Ý tưởng sáng tạo thăng hoa, tầm nhìn vượt thời đại." },
    { key: "bơi", numbers: "14, 41", soul: "Đang nỗ lực thích nghi với môi trường mới đầy thử thách." },
    { key: "ngã", numbers: "16, 61", soul: "Cẩn thận trong các quyết định quan trọng sắp tới." },
    { key: "xây nhà", numbers: "14, 41", soul: "Đang đặt nền móng vững chắc cho tương lai." },
    { key: "cháy nhà", numbers: "05, 43, 67", soul: "Cẩn thận nóng nảy làm hỏng việc lớn." },
    { key: "đi học", numbers: "17, 71", soul: "Cần trau dồi thêm kiến thức để bứt phá." },
    { key: "mang thai", numbers: "09, 29, 39", soul: "Một ý tưởng hoặc dự án mới đang được ấp ủ." },
    { key: "hôn", numbers: "00, 48, 84", soul: "Sự giao thoa cảm xúc đang ở giai đoạn thăng hoa nhất." },
    { key: "chạy", numbers: "12, 21", soul: "Bạn đang cố gắng thoát khỏi một áp lực vô hình." },
    { key: "khỏa thân", numbers: "18, 81", soul: "Bạn đang muốn sống thật với bản thân, không che giấu." },
    { key: "mất đồ", numbers: "01, 10", soul: "Hãy kiểm tra lại những giá trị cốt lõi bạn đang nắm giữ." }

    // --- CHỦ ĐỀ: CƠ THỂ & SỨC KHỎE ---
    { key: "đau bụng", numbers: "09, 90", soul: "Có chuyện khó nói đang kìm nén trong lòng." },
    { key: "gãy tay", numbers: "12, 21", soul: "Cẩn thận trong công việc, tránh ôm đồm quá sức." },
    { key: "gãy chân", numbers: "34, 43", soul: "Tiến độ công việc có thể bị chậm lại một nhịp." },
    { key: "đau răng", numbers: "07, 17", soul: "Có lời ra tiếng vào không hay về tài chính." },
    { key: "chảy máu mũi", numbers: "19, 91", soul: "Áp lực tinh thần đang ở mức báo động." },
    { key: "cắt móng tay", numbers: "14, 41", soul: "Bạn đang chủ động loại bỏ những rắc rối nhỏ." },
    { key: "nhức đầu", numbers: "01, 10", soul: "Quá nhiều dự án đang làm bạn rối bời." },
    { key: "mù mắt", numbers: "00, 11", soul: "Đừng để cái lợi trước mắt làm mờ ý chí." },
    { key: "tai ù", numbers: "03, 30", soul: "Sắp nhận được tin đồn thất thiệt." },
    { key: "đi khập khiễng", numbers: "09, 49", soul: "Dự án đang thiếu sự cân bằng, cần điều chỉnh." },

    // --- CHỦ ĐỀ: ĐỒ GIA DỤNG & CÔNG TRÌNH ---
    { key: "tủ lạnh", numbers: "05, 50", soul: "Tài lộc đang được tích trữ tốt, cứ yên tâm." },
    { key: "máy giặt", numbers: "11, 22", soul: "Mọi rắc rối sẽ sớm được tẩy rửa sạch sẽ." },
    { key: "cái chổi", numbers: "01, 41", soul: "Sắp có cuộc 'tổng vệ sinh' nhân sự hoặc ý tưởng." },
    { key: "cái giường", numbers: "02, 22", soul: "Cần một khoảng lặng để tái tạo sức lao động." },
    { key: "cửa sổ", numbers: "06, 66", soul: "Hướng đi mới đang mở ra, hãy nhìn rộng hơn." },
    { key: "cái gương", numbers: "07, 77", soul: "Tự soi xét lại mình trước khi trách người khác." },
    { key: "bàn thờ", numbers: "05, 55", soul: "Bề trên đang nhắc nhở bạn giữ vững đạo đức." },
    { key: "nhà vệ sinh", numbers: "08, 09", soul: "Nơi trút bỏ gánh nặng, sắp được nhẹ lòng." },
    { key: "cầu thang", numbers: "02, 20", soul: "Từng bước thăng tiến, không nên vội vàng." },
    { key: "bể nước", numbers: "06, 60", soul: "Nguồn tài chính dồi dào, không lo cạn kiệt." },
    { key: "cái thớt", numbers: "13, 31", soul: "Cẩn thận bị cấp trên 'thọc gậy bánh xe'." },
    { key: "cái bát", numbers: "01, 10", soul: "Công việc kinh doanh đang đi vào quỹ đạo." },
    { key: "đũa", numbers: "02, 20", soul: "Sự hợp tác song phương mang lại kết quả tốt." },

    // --- CHỦ ĐỀ: THIÊN NHIÊN & THỜI TIẾT CỰC ĐOAN ---
    { key: "động đất", numbers: "05, 95", soul: "Sắp có biến động lớn trong ngành game của bạn." },
    { key: "sóng thần", numbers: "10, 50", soul: "Khó khăn dồn dập, cần bản lĩnh để vượt qua." },
    { key: "núi lửa", numbers: "07, 77", soul: "Cơn giận dữ bùng phát hỏng việc lớn, hãy kiềm chế." },
    { key: "tuyết rơi", numbers: "00, 11", soul: "Mọi thứ đang đóng băng, hãy chờ thời điểm khác." },
    { key: "cầu vồng", numbers: "07, 70", soul: "Sau cơn mưa trời lại sáng, thành công rực rỡ." },
    { key: "sét đánh", numbers: "13, 31", soul: "Tin sét đánh ngang tai về một dự án bị hủy." },
    { key: "lũ lụt", numbers: "06, 66", soul: "Cẩn thận bị cuốn trôi bởi những hư vinh ảo." },
    { key: "sa mạc", numbers: "15, 51", soul: "Bạn đang cô độc trong chính ý tưởng của mình." },
    { key: "hang động", numbers: "03, 33", soul: "Khám phá ra một 'ngách' thị trường cực ngon." },
    { key: "rừng rậm", numbers: "14, 41", soul: "Nhiều cạm bẫy phía trước, cần người dẫn đường." },

    // --- CHỦ ĐỀ: PHƯƠNG TIỆN & CÔNG CỤ ĐẶC THÙ ---
    { key: "xe tăng", numbers: "05, 55", soul: "Sức mạnh áp đảo, không ai cản bước được bạn." },
    { key: "máy xúc", numbers: "11, 21", soul: "Đang đào sâu vào một vấn đề nan giải." },
    { key: "cần cẩu", numbers: "12, 22", soul: "Có sự giúp đỡ từ phía 'ông lớn'." },
    { key: "xích lô", numbers: "03, 30", soul: "Cuộc sống thong dong, không cần vội vã." },
    { key: "khinh khí cầu", numbers: "05, 50", soul: "Lãng mạn nhưng thiếu thực tế, hãy tiếp đất đi." },
    { key: "phi thuyền", numbers: "00, 99", soul: "Ý tưởng vượt tầm vũ trụ, chuẩn bị bùng nổ." },
    { key: "xe rác", numbers: "07, 70", soul: "Hãy vứt bỏ những tư duy cũ kỹ độc hại." },
    { key: "xe cứu thương", numbers: "08, 11", soul: "Cần sự hỗ trợ khẩn cấp về tài chính." },
    { key: "xe cứu hỏa", numbers: "07, 11", soul: "Sắp phải đi giải quyết hậu quả cho người khác." },
    { key: "thuyền thúng", numbers: "01, 11", soul: "Sự chông chênh trong các quyết định hiện tại." },

    // --- CHỦ ĐỀ: HÀNH ĐỘNG & TRẠNG THÁI ---
    { key: "đi câu cá", numbers: "01, 81", soul: "Đang kiên nhẫn chờ đợi một cơ hội béo bở." },
    { key: "đi hái quả", numbers: "39, 49", soul: "Sắp đến ngày thu hoạch thành quả lao động." },
    { key: "bị bắt cóc", numbers: "04, 44", soul: "Bạn đang bị gò bó bởi những quy tắc cứng nhắc." },
    { key: "đi lạc đường", numbers: "21, 31", soul: "Mất phương hướng, hãy dừng lại để nhìn bản đồ cuộc đời." },
    { key: "leo núi", numbers: "05, 55", soul: "Chinh phục đỉnh cao đòi hỏi sự bền bỉ." },
    { key: "bơi lội", numbers: "14, 41", soul: "Thích nghi tốt với môi trường cạnh tranh khốc liệt." },
    { key: "nhảy dù", numbers: "05, 95", soul: "Mạo hiểm mang lại kết quả bất ngờ." },
    { key: "đọc sách", numbers: "17, 71", soul: "Ki thức sẽ giúp bạn vượt qua giai đoạn này." },
    { key: "xem phim", numbers: "18, 81", soul: "Bạn đang đứng ngoài cuộc chơi, hãy tham gia vào." },
    { key: "chụp ảnh", numbers: "07, 70", soul: "Muốn lưu giữ những khoảnh khắc huy hoàng." },
    { key: "đi bộ", numbers: "01, 10", soul: "Tiến triển chậm nhưng chắc chắn." },
    { key: "chạy trốn", numbers: "12, 21", soul: "Trốn tránh trách nhiệm không phải cách hay." },
    { key: "nhảy múa", numbers: "26, 62", soul: "Niềm vui ngập tràn, tinh thần đang lên cao." },
    { key: "ca hát", numbers: "16, 61", soul: "Muốn thể hiện bản thân trước đám đông." },
    { key: "viết thư", numbers: "01, 05", soul: "Lời nhắn gửi quan trọng sắp được gửi đi." },
    { key: "tưới cây", numbers: "07, 70", soul: "Chăm chút cho tương lai một cách âm thầm." },
    { key: "quét nhà", numbers: "01, 41", soul: "Loại bỏ những thứ không còn giá trị." },
    { key: "giặt đồ", numbers: "11, 21", soul: "Chuẩn bị cho một sự khởi đầu mới tinh khôi." },
    { key: "đi du lịch", numbers: "12, 21", soul: "Cần một làn gió mới để đổi vận." },
    { key: "mất ngủ", numbers: "00, 11", soul: "Sự lo âu đang gặm nhấm tâm hồn bạn." },

    // --- CHỦ ĐỀ: CON VẬT KHÁC ---
    { key: "con dơi", numbers: "15, 55", soul: "Điềm báo về bóng tối hoặc sự huyền bí." },
    { key: "con đại bàng", numbers: "25, 65", soul: "Sức mạnh đỉnh cao, tầm nhìn bao quát." },
    { key: "con công", numbers: "14, 44", soul: "Sự kiêu hãnh và vẻ đẹp nổi bật." },
    { key: "con khỉ", numbers: "48, 84", soul: "Cẩn thận bị người khác chơi xỏ, lừa lọc." },
    { key: "con gà rừng", numbers: "28, 82", soul: "Tự do và may mắn từ thiên nhiên." },
    { key: "con cá mập", numbers: "09, 90", soul: "Đối thủ đáng gờm đang rình rập." },
    { key: "con bạch tuộc", numbers: "08, 88", soul: "Rắc rối đan xen, cần gỡ rối từng chút một." },
    { key: "con tôm", numbers: "31, 91", soul: "Có chuyện thị phi nhỏ nhưng không đáng lo." },
    { key: "con cua", numbers: "10, 40", soul: "Sự cứng đầu sẽ làm hỏng kế hoạch chung." },
    { key: "con kiến", numbers: "05, 55", soul: "Kiên trì gom góp sẽ có kho tàng lớn." },
    { key: "con ong", numbers: "16, 56", soul: "Chăm chỉ sẽ được đền đáp bằng mật ngọt." },
    { key: "con sâu", numbers: "05, 50", soul: "Sắp có sự lột xác mạnh mẽ để thành bướm." },

    // --- CHỦ ĐỀ: TỔNG HỢP ---
    { key: "nghĩa địa", numbers: "03, 33", soul: "Quá khứ đã ngủ yên, hãy sống cho hiện tại." },
    { key: "quan tài", numbers: "06, 26, 56", soul: "Thăng quan tiến chức, phát lộc phát tài." },
    { key: "vết thương", numbers: "12, 21", soul: "Nỗi đau cũ vẫn còn, hãy học cách chữa lành." },
    { key: "vàng giả", numbers: "08, 80", soul: "Cẩn thận bị lừa bởi vẻ bề ngoài hào nhoáng." },
    { key: "kim cương", numbers: "44, 88", soul: "Giá trị bản thân đang được khẳng định." },
    { key: "ngọc trai", numbers: "01, 11", soul: "Vẻ đẹp tâm hồn mang lại may mắn." },
    { key: "súng đạn", numbers: "11, 21", soul: "Lời nói sắc bén có thể gây sát thương." },
    { key: "bom nổ", numbers: "00, 99", soul: "Sự bùng nổ bất ngờ, chấn động cả ngành." },
    { key: "nhà tù", numbers: "04, 44", soul: "Cảm giác bị giam cầm ý tưởng, cần thoát ra." },
    { key: "tòa án", numbers: "13, 31", soul: "Công lý sẽ thực thi, bạn không cần lo lắng." },
    { key: "đám mây", numbers: "09, 90", soul: "Mọi thứ còn mơ hồ, hãy chờ mây tan." },
    { key: "mặt trăng", numbers: "02, 22", soul: "Trực giác mách bảo bạn điều đúng đắn." },
    { key: "mặt trời", numbers: "01, 11", soul: "Sức mạnh và chân lý luôn bên bạn." },
    { key: "vì sao", numbers: "05, 55", soul: "Hy vọng và ước mơ sắp thành hiện thực." },
    { key: "ma vương", numbers: "00, 66", soul: "Đối mặt với bóng tối trong chính mình." },
    { key: "thiên thần", numbers: "01, 88", soul: "Có sự bảo hộ vô hình giúp bạn vượt qua." },
    { key: "tượng Phật", numbers: "01, 91", soul: "Tâm đức sáng suốt, mọi sự hanh thông." },
    { key: "bàn ghế", numbers: "03, 30", soul: "Sắp có sự thay đổi về vị trí làm việc." },
    { key: "mũ nón", numbers: "06, 60", soul: "Che chở và bảo vệ thành quả lao động." },
    { key: "giày dép", numbers: "09, 90", soul: "Chuẩn bị cho những bước đi vững chắc hơn." }

// --- CHỦ ĐỀ: VŨ KHÍ & ĐỒ CỔ ---
    { key: "cung tên", numbers: "39, 93", soul: "Mục tiêu đã định, chỉ chờ thời điểm bóp cò." },
    { key: "áo giáp", numbers: "08, 88", soul: "Bạn đang tự vệ quá mức, hãy mở lòng hơn." },
    { key: "thành quách", numbers: "46, 64", soul: "Sự kiên cố và bảo thủ đang kìm hãm bạn." },
    { key: "thanh kiếm", numbers: "12, 21", soul: "Sự quyết đoán mang lại uy quyền tối thượng." },
    { key: "vương miện", numbers: "01, 11", soul: "Trách nhiệm đi kèm với vinh quang rực rỡ." },
    { key: "đèn lồng", numbers: "05, 50", soul: "Một chỉ dẫn nhỏ sẽ giúp bạn thoát khỏi u tối." },
    { key: "bình cổ", numbers: "37, 73", soul: "Giá trị thực sự nằm ở kinh nghiệm tích lũy." },
    { key: "ngọc ấn", numbers: "09, 99", soul: "Lời nói của bạn có sức nặng ngàn cân lúc này." },

    // --- CHỦ ĐỀ: NHẠC CỤ & NGHỆ THUẬT ---
    { key: "đàn piano", numbers: "22, 44", soul: "Cuộc sống cần sự nhịp nhàng và tinh tế hơn." },
    { key: "đàn guitar", numbers: "16, 61", soul: "Tâm hồn lãng tử, khao khát tự do tự tại." },
    { key: "tiếng trống", numbers: "08, 80", soul: "Tin vui dồn dập, khí thế đang hừng hực." },
    { key: "tiếng sáo", numbers: "03, 30", soul: "Sự thanh thản và cô độc đầy thi vị." },
    { key: "ống sáo", numbers: "06, 60", soul: "Mọi việc hanh thông nhờ sự khéo léo của bạn." },
    { key: "sân khấu", numbers: "25, 52", soul: "Đã đến lúc bạn bước ra ánh sáng tỏa sáng." },
    { key: "tượng đá", numbers: "07, 70", soul: "Sự lạnh lùng đang khiến mọi người xa cách bạn." },

    // --- CHỦ ĐỀ: CÔN TRÙNG & SINH VẬT NHỎ ---
    { key: "con gián", numbers: "49, 94", soul: "Sức sống bền bỉ trong điều kiện khắc nghiệt nhất." },
    { key: "con muỗi", numbers: "05, 50", soul: "Những rắc rối nhỏ nhặt đang làm bạn khó chịu." },
    { key: "con ruồi", numbers: "19, 91", soul: "Phiền phức đeo bám, cần dứt khoát loại bỏ." },
    { key: "con sâu bướm", numbers: "06, 66", soul: "Giai đoạn chuẩn bị cho một cuộc lột xác vĩ đại." },
    { key: "con kiến lửa", numbers: "15, 51", soul: "Sự đoàn kết sẽ tạo nên sức mạnh vô song." },
    { key: "con vắt", numbers: "02, 22", soul: "Cẩn thận bị lợi dụng sức lao động hoặc tiền bạc." },
    { key: "con đỉa", numbers: "43, 34", soul: "Mối quan hệ độc hại đang bòn rút năng lượng của bạn." },
    { key: "con bọ hung", numbers: "09, 90", soul: "Công việc nặng nhọc nhưng sẽ mang lại thành quả." },
    { key: "con sâu răng", numbers: "03, 30", soul: "Vấn đề tiềm ẩn bên trong bắt đầu phát tác." },

    // --- CHỦ ĐỀ: ĐỒ ĂN VẶT & ĐỒ UỐNG HIỆN ĐẠI ---
    { key: "trà sữa", numbers: "02, 22", soul: "Niềm vui nhỏ bé giúp xua tan căng thẳng hằng ngày." },
    { key: "mì tôm", numbers: "01, 10", soul: "Giai đoạn thắt lưng buộc bụng để chờ thời cơ lớn." },
    { key: "kem tươi", numbers: "03, 30", soul: "Sự ngọt ngào nhưng dễ tan chảy, hãy nắm bắt ngay." },
    { key: "pizza", numbers: "08, 88", soul: "Sự chia sẻ quyền lợi công bằng trong nhóm làm game." },
    { key: "đùi gà", numbers: "28, 82", soul: "Phần thưởng xứng đáng cho sự nỗ lực của bạn." },
    { key: "xúc xích", numbers: "11, 22", soul: "Mọi thứ diễn ra theo dây chuyền, hãy cẩn thận khâu cuối." },
    { key: "nước cam", numbers: "05, 50", soul: "Nguồn năng lượng tươi mới đang tràn về." },

    // --- CHỦ ĐỀ: TRẠNG THÁI HỎNG HÓC & SỰ CỐ ---
    { key: "cháy túi", numbers: "00, 11", soul: "Bài học về quản lý tài chính xương máu." },
    { key: "thủng lốp xe", numbers: "02, 20", soul: "Sự cố bất ngờ làm gián đoạn kế hoạch quan trọng." },
    { key: "mất mạng", numbers: "00, 10", soul: "Sự kết nối bị đứt gãy, cần tìm cách liên lạc khác." },
    { key: "hết pin", numbers: "04, 40", soul: "Bạn đã kiệt sức, hãy nghỉ ngơi trước khi gục ngã." },
    { key: "rơi điện thoại", numbers: "07, 70", soul: "Sự bất cẩn dẫn đến thiệt hại đáng tiếc." },
    { key: "vỡ màn hình", numbers: "11, 17", soul: "Tầm nhìn bị hạn chế, cần sửa sang lại kế hoạch." },
    { key: "mất điện", numbers: "00, 01", soul: "Tạm thời mất phương hướng, hãy chờ đợi ánh sáng." },
    { key: "tắc đường", numbers: "35, 53", soul: "Mọi thứ đang dậm chân tại chỗ, cần sự kiên nhẫn." },

    // --- CHỦ ĐỀ: HÀNH ĐỘNG KỲ QUẶC & HIỆN ĐẠI ---
    { key: "đi vệ sinh công cộng", numbers: "34, 43", soul: "Sự riêng tư bị xâm phạm, hãy cẩn thận bí mật của bạn." },
    { key: "nhặt được vàng", numbers: "37, 73", soul: "Vận may bất ngờ, nhưng của thiên trả địa nếu không khéo." },
    { key: "bị sếp mắng", numbers: "21, 26", soul: "Lời phê bình sẽ giúp bạn hoàn thiện sản phẩm hơn." },
    { key: "đi dạo công viên", numbers: "15, 51", soul: "Tâm hồn thảnh thơi, ý tưởng mới sẽ nảy nở." },
    { key: "đi xem bói", numbers: "08, 88", soul: "Bạn đang quá phụ thuộc vào ý kiến người khác." },
    { key: "bị chó cắn", numbers: "29, 92", soul: "Cẩn thận bị người thân tín phản bội." },
    { key: "đi chợ mua cá", numbers: "01, 81", soul: "Đang tính toán một thương vụ kinh doanh nhỏ." },
    { key: "trèo tường", numbers: "04, 44", soul: "Bạn đang tìm cách lách luật để đạt mục đích." },
    { key: "đi xem xiếc", numbers: "13, 31", soul: "Cuộc sống xung quanh bạn đang quá màu mè, giả tạo." },
    { key: "gội đầu", numbers: "39, 93", soul: "Rửa trôi những suy nghĩ đen tối, u ám." },
    { key: "soi gương trang điểm", numbers: "07, 77", soul: "Sự tự tin thái quá đôi khi là điểm yếu." },
    { key: "đi mua sắm", numbers: "06, 60", soul: "Nhu cầu khẳng định bản thân thông qua vật chất." },

    // --- CHỦ ĐỀ: CÁC KHÁI NIỆM TRỪU TƯỢNG ---
    { key: "điểm 10", numbers: "01, 10", soul: "Sự hoàn hảo mà bạn luôn hướng tới sắp đạt được." },
    { key: "điểm 0", numbers: "00, 10", soul: "Thất bại là mẹ thành công, đừng nản lòng." },
    { key: "kho báu", numbers: "39, 79", soul: "Năng lực tiềm ẩn trong bạn sắp được khai phá." },
    { key: "lỗ đen", numbers: "00, 99", soul: "Cẩn thận bị cuốn vào những việc không có lối thoát." },
    { key: "vòng xoáy", numbers: "08, 80", soul: "Sự luẩn quẩn trong suy nghĩ, cần bứt phá." },
    { key: "ánh hào quang", numbers: "11, 88", soul: "Vinh quang đang chờ đón bạn phía cuối con đường." },
    { key: "bóng tối", numbers: "00, 11", soul: "Nỗi sợ hãi lớn nhất chính là bản thân bạn." },
    { key: "thiên hà", numbers: "05, 55", soul: "Ý tưởng của bạn có tầm ảnh hưởng cực lớn." },

    // --- CHỦ ĐỀ: THIÊN NHIÊN & CÔNG TRÌNH KHÁC ---
    { key: "suối nước nóng", numbers: "39, 93", soul: "Sự thư giãn tuyệt đối, cơ thể đang hồi phục." },
    { key: "thác nước", numbers: "06, 66", soul: "Tiền tài đổ về như nước, không gì cản nổi." },
    { key: "ruộng lúa", numbers: "07, 70", soul: "Sự ấm no và thành quả từ sự cần cù lao động." },
    { key: "ngọn hải đăng", numbers: "01, 11", soul: "Sự dẫn lối đúng đắn trong lúc hoạn nạn." },
    { key: "đập thủy điện", numbers: "11, 22", soul: "Năng lượng dồi dào đang được tích lũy chờ bùng nổ." },
    { key: "cây cổ thụ", numbers: "05, 55", soul: "Sự bảo hộ vững chắc từ những người đi trước." },
    { key: "vườn hoa", numbers: "15, 51", soul: "Tình duyên chớm nở, cuộc sống tràn ngập màu sắc." },
    { key: "sa mạc cát", numbers: "13, 31", soul: "Sự khô hạn trong cảm hứng sáng tạo." },
    { key: "núi tuyết", numbers: "00, 11", soul: "Khó khăn thử thách nhưng cảnh sắc tuyệt vời." },

    // --- CHỦ ĐỀ: NHÂN VẬT PHỤ & KỲ LẠ ---
    { key: "ông già Noel", numbers: "12, 25", soul: "Phần thưởng bất ngờ dành cho người xứng đáng." },
    { key: "chú hề", numbers: "03, 33", soul: "Tiếng cười đằng sau sự cô đơn, hãy chia sẻ nhiều hơn." },
    { key: "người khổng lồ", numbers: "05, 50", soul: "Bạn đang đối mặt với một vấn đề quá tầm tay." },
    { key: "người lùn", numbers: "01, 10", soul: "Đừng coi thường những chi tiết nhỏ trong game." },
    { key: "phù thủy", numbers: "06, 66", soul: "Sự biến hóa khôn lường, cẩn thận bị mê hoặc." },
    { key: "tiên nữ", numbers: "09, 99", soul: "Sự giúp đỡ dịu dàng và thanh khiết từ quý nhân nữ." },
    { key: "siêu nhân", numbers: "01, 11", soul: "Khát khao trở thành người hùng cứu rỗi dự án." },
    { key: "ăn trộm tiền", numbers: "14, 41", soul: "Cẩn thận hao tài tốn của vì người lạ." },
    { key: "ăn trộm xe", numbers: "07, 70", soul: "Mất đi phương tiện hoặc cơ hội thăng tiến." },
    { key: "cảnh sát rượt đuổi", numbers: "14, 41", soul: "Áp lực lương tâm về một hành động sai lầm." },

    // --- CHỦ ĐỀ: ĐỒ VẬT LINH TINH ---
    { key: "cái nôi", numbers: "09, 19", soul: "Dự án mới đang được nâng niu, chăm sóc." },
    { key: "cái quan tài", numbers: "06, 26, 56", soul: "Phát tài phát lộc, một sự kết thúc để bắt đầu mới." },
    { key: "nghĩa trang", numbers: "03, 33", soul: "Buông bỏ quá khứ, hướng tới tương lai rực rỡ." },
    { key: "cái búa nhựa", numbers: "01, 11", soul: "Sức mạnh ảo, đừng quá tự tin vào vũ khí hiện tại." },
    { key: "cái kéo gãy", numbers: "06, 60", soul: "Mối quan hệ bị rạn nứt không thể hàn gắn." },
    { key: "cái lược gãy", numbers: "03, 30", soul: "Rắc rối trong tình cảm không thể chải chuốt." },
    { key: "cái kính vỡ", numbers: "07, 70", soul: "Cái nhìn sai lệch về thực tế, cần tỉnh táo lại." },
    { key: "đôi tất", numbers: "02, 22", soul: "Sự ấm áp và quan tâm từ những điều nhỏ nhất." },
    { key: "cái khăn quàng", numbers: "06, 66", soul: "Sự che chở và gắn kết tình cảm bền chặt." },
    { key: "cái thắt lưng", numbers: "05, 50", soul: "Cần siết chặt chi tiêu và kỷ luật bản thân." },
    { key: "cái ô che nắng", numbers: "08, 88", soul: "Sắp có quý nhân che chắn khỏi thị phi." },
    { key: "cái diều", numbers: "05, 50", soul: "Bay cao nhờ gió, hãy tận dụng thời thế." },
    { key: "hòm tiền", numbers: "39, 79", soul: "Tiền của đang tích tụ, chuẩn bị nổ hũ lớn." },
    { key: "chùm chìa khóa", numbers: "01, 10", soul: "Bạn đang nắm giữ nhiều giải pháp cho cùng một vấn đề." }
];
